version: '3.8'

services:
  db:
    image: postgres:14
    container_name: med_res_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: meddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: med_res_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Ustawienia połączenia do PostgreSQL – aplikacja odczyta je z env variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # (opcjonalnie) wyłączamy konsolę H2, bo teraz używamy PostgreSQL
      # W przypadku gdy wciąż chcemy mieć H2, można to pominąć
      spring.h2.console.enabled: "false"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
